<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="1" tests="3" time="2.739">
 <testsuite name="Logon M4Nodejs Suite Pila" timestamp="2020-03-04T11:06:37" hostname="localhost" time="2.739" errors="0" tests="3" skipped="0" disabled="0" failures="1">
  <testcase classname="Logon M4Nodejs Suite Pila" name="Should create an instance" time="0" />
  <testcase classname="Logon M4Nodejs Suite Pila" name="Should do logon" time="0.367" />
  <testcase classname="Logon M4Nodejs Suite Pila" name="Should execute Colombia Pila" time="2.158">
   <failure type="exception" message="[object Object] thrown"><![CDATA[[object Object] thrown]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>