<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="1" tests="3" time="4.355">
 <testsuite name="Logon M4Nodejs Suite Pila" timestamp="2020-03-04T13:16:13" hostname="localhost" time="4.355" errors="0" tests="3" skipped="0" disabled="0" failures="1">
  <testcase classname="Logon M4Nodejs Suite Pila" name="Should create an instance" time="0" />
  <testcase classname="Logon M4Nodejs Suite Pila" name="Should do logon" time="0.381" />
  <testcase classname="Logon M4Nodejs Suite Pila" name="Should execute Colombia Pila" time="3.766">
   <failure type="exception" message="moveTo: Invalid index 34 thrown"><![CDATA[moveTo: Invalid index 34 thrown]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>