<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="1" tests="3" time="51.7">
 <testsuite name="Logon M4Nodejs Suite" timestamp="2020-03-03T12:54:24" hostname="localhost" time="51.7" errors="0" tests="3" skipped="0" disabled="0" failures="1">
  <testcase classname="Logon M4Nodejs Suite" name="Should create an instance" time="0.001" />
  <testcase classname="Logon M4Nodejs Suite" name="Should do logon" time="50.13" />
  <testcase classname="Logon M4Nodejs Suite" name="Should load employee name" time="1.291">
   <failure type="exception" message="Invalid node PLCO_PERSONAL_EMPLOYEE_INFORMIT in object PLCO_LOAD_ALL_PERSONAL_INFO thrown"><![CDATA[Invalid node PLCO_PERSONAL_EMPLOYEE_INFORMIT in object PLCO_LOAD_ALL_PERSONAL_INFO thrown]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>